added bcryptjs
heroku logs is still showing:
Error: Cannot find module 'bcrypt'
2025-02-12T01:44:03.455577+00:00 app[web.1]: Require stack:
2025-02-12T01:44:03.455578+00:00 app[web.1]: - /app/models.js
2025-02-12T01:44:03.455578+00:00 app[web.1]: - /app/index.js